version: '3'

services:
  tcp:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=docker
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
